companies:
  - name: "Solidus Ai Tech"
    ticker: "AITECH-USD"
    source: "https://finance.yahoo.com/quote/AITECH-USD/"

analysis_points:
  financial_metrics:
    - "収益成長率"
    - "営業利益率"
    - "ROE"
  market_position:
    - "市場シェア"
    - "競争優位性"
  technology:
    - "研究開発投資"
    - "特許ポートフォリオ"
  sentiment:
    - "アナリスト評価"
    - "SNSでの評判"

metadata:
  model: "gpt-4o-mini"
  version: "1.0"
  date: "2025/01/23"
