companies:
  - name: NVIDIA
  - name: Microsoft
  - name: Google
  - name: Meta
  - name: Palantir Technologies
  - name: Rocket Lab
  - name: First Solar
  - name: Cloudflare
  - name: MongoDB
  - name: Snowflake
  - name: Unity Software
  - name: AI Tech Corp
  - name: Data Systems Inc
  - name: Solidus Ai Tech USD
